from typing import TypedDict


class ChatbotState(TypedDict, total=False):
    """
    Minimal shared state for the LLM chatbot prototype.

    This state is intentionally lightweight in order to test
    raw LLM behavior before introducing orchestration,
    specialized routing, or structured decision pipelines.
    """

    user_query: str
    # Raw natural-language question submitted by the user.

    answer: str
    # Final answer generated by the chatbot.

    model_used: str
    # Name of the model used to generate the answer.

    error: str
    # Optional error message captured during execution.