from typing import TypedDict
from src.agent.schemas_chatbot import StructuredChatbotOutput


# class ChatbotState(TypedDict, total=False):
#     """
#     Minimal shared state for the LLM chatbot prototype.

#     This state is intentionally lightweight in order to test
#     raw LLM behavior before introducing orchestration,
#     specialized routing, or structured decision pipelines.
#     """

#     user_query: str
#     # Raw natural-language question submitted by the user.

#     answer: str
#     # Final answer generated by the chatbot.

#     model_used: str
#     # Name of the model used to generate the answer.

#     error: str
#     # Optional error message captured during execution.

#     from typing import Optional, TypedDict


class ChatbotState(TypedDict, total=False):
    """
    Shared state for the structured chatbot prototype.

    This V2.1 state moves from raw text answers to a structured,
    machine-readable output that can later feed retrieval,
    rule-based validation, and decision scoring.
    """

    user_query: str
    # Raw natural-language question submitted by the user.

    structured_output: dict
    # JSON-serializable structured output returned by the LLM.

    model_used: str
    # Name of the model used to generate the output.

    error: str
    # Optional error message captured during execution.